---

- name: configure | create (load-balancer) configuration file
  template:
    src: etc/rstudio/load-balancer.j2
    dest: /etc/rstudio/load-balancer
    owner: root
    group: root
    mode: 0644
  notify: restart rstudio-workbench
  tags:
    - rstudio-workbench-configure-load-balancer

- name: configure | create (secure-cookie-key) file
  copy:
    content: "{{ rstudio_workbench_secure_cookie_key }}"
    dest: /etc/rstudio/secure_cookie_key
    owner: root
    group: root
    mode: 0600
  notify: restart rstudio-workbench
  tags:
    - rstudio-workbench-configure-load-balancer
