---

- name: Configure | update (server) configuration file
  ansible.builtin.template:
    src: etc/rstudio/rserver.conf.j2
    dest: /etc/rstudio/rserver.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart rstudio-workbench

- name: Configure | create (SSO metadata xml) file
  ansible.builtin.copy:
    content: "{{ rstudio_workbench_sso_saml_metadata_content_b64_encoded | b64decode }}"
    dest: "{{ rstudio_workbench_sso_saml_metadata_file_path }}"
    owner: rstudio-server
    group: root
    mode: 0600
  notify: Restart rstudio-workbench
  when:
    - rstudio_workbench_sso_saml_metadata_content_b64_encoded|d()
    - rstudio_workbench_sso_saml_metadata_file_path|d()

- name: Configure | update (session) configuration file
  ansible.builtin.template:
    src: etc/rstudio/rsession.conf.j2
    dest: /etc/rstudio/rsession.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart rstudio-workbench

- name: Configure | logging configuration file
  ansible.builtin.template:
    src: etc/rstudio/logging.conf.j2
    dest: /etc/rstudio/logging.conf
    owner: root
    group: root
    mode: 0644
  when:
    - rstudio_workbench_logging_config is defined
  notify: Restart rstudio-workbench

- name: Configure | create (database) configuration file
  ansible.builtin.template:
    src: etc/rstudio/database.conf.j2
    dest: /etc/rstudio/database.conf
    owner: root
    group: root
    mode: 0600
  when:
    - rstudio_workbench_database_config is defined
  notify: Restart rstudio-workbench

- name: Configure | update (profiles) configuration file
  ansible.builtin.template:
    src: etc/rstudio/profiles.j2
    dest: /etc/rstudio/profiles
    owner: root
    group: root
    mode: 0644
  when:
    - rstudio_workbench_profiles_config is defined

- name: Configure | update pam profile
  ansible.builtin.template:
    src: etc/pam.d/rstudio.j2
    dest: /etc/pam.d/rstudio
    owner: root
    group: root
    mode: 0644
  when:
    - rstudio_workbench_pam_profile is defined
  notify: Restart rstudio-workbench

- name: Configure | create sssd service config
  ansible.builtin.template:
    src: etc/sssd/sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600
  notify:
    - Restart sssd
  when:
    - rstudio_workbench_sssd_config is defined

- name: Include configure-lb
  ansible.builtin.include_tasks: configure-lb.yml
  when:
    - rstudio_workbench_load_balancer_config is defined
    - rstudio_workbench_database_config is defined
    - rstudio_workbench_secure_cookie_key is defined
    - rstudio_workbench_secure_cookie_key|length

- name: Configure | make sure shared-storage directory exists
  ansible.builtin.file:
    path: "{{ rstudio_workbench_rserver_config['server-shared-storage-path'] }}"
    state: directory
    mode: 0755
  when:
    - rstudio_workbench_rserver_config['server-shared-storage-path'] is defined

- name: Configure | make sure shared users home directory exists
  ansible.builtin.file:
    path: "{{ rstudio_workbench_users_home_dir }}"
    state: directory
    mode: 0755
  when:
    - rstudio_workbench_users_home_dir is defined

- name: Include configure-launcher
  ansible.builtin.import_tasks: configure-launcher.yml
  notify:
    - Restart rstudio-job-launcher

- name: Configure | create (openid) configuration file
  ansible.builtin.template:
    src: etc/rstudio/openid-client-secret.j2
    dest: /etc/rstudio/openid-client-secret
    owner: root
    group: root
    mode: 0600
  when:
    - rstudio_workbench_openid_config is defined

- name: Configure | link (env-vars) file
  ansible.builtin.file:
    src: "{{ rstudio_workbench_env_vars_file_path }}"
    dest: /etc/rstudio/env-vars
    owner: root
    group: root
    state: link
  when:
    - rstudio_workbench_env_vars_file_path is defined
    - rstudio_workbench_env_vars_file_path|length
    - rstudio_workbench_env_vars is not defined

- name: Configure | create (env-vars) file
  ansible.builtin.template:
    src: etc/rstudio/env-vars.j2
    dest: /etc/rstudio/env-vars
    owner: root
    group: root
    mode: 0644
  when:
    - rstudio_workbench_env_vars is defined

- name: Configure | create (repos.conf) file
  ansible.builtin.template:
    src: etc/rstudio/repos.conf.j2
    dest: /etc/rstudio/repos.conf
    owner: root
    group: root
    mode: 0644
  when:
    - rstudio_workbench_repos_config is defined

- name: Configure | license activation (offline)
  notify: Restart rstudio-workbench
  when: rstudio_workbench_license_offline_key_b64_encoded | d()
  no_log: true
  block:
    - name: License activation (offline) | upload key file
      ansible.builtin.copy:
        content: "{{ rstudio_workbench_license_offline_key_b64_encoded | b64decode }}"
        dest: "/etc/rstudio/activation-key.lic"
        owner: root
        group: root
        mode: 0600

    - name: License activation (offline) | activate using key file  # noqa no-changed-when
      ansible.builtin.shell: |
        /usr/sbin/rstudio-server license-manager activate-file /etc/rstudio/activation-key.lic

- name: Configure | license activation (online)
  ansible.builtin.shell: |
    /usr/sbin/rstudio-server license-manager activate {{ rstudio_workbench_license }}
  notify: Restart rstudio-workbench
  register: license_output
  when: rstudio_workbench_license | d()
  no_log: true
