---

- name: Configure | create (load-balancer) configuration file
  ansible.builtin.template:
    src: etc/rstudio/load-balancer.j2
    dest: /etc/rstudio/load-balancer
    owner: root
    group: root
    mode: 0644
  when:
    - rstudio_workbench_load_balancer_config is defined
    - rstudio_workbench_load_balancer_config|length

- name: Configure | create (secure-cookie-key) file
  ansible.builtin.copy:
    content: "{{ rstudio_workbench_secure_cookie_key }}"
    dest: /etc/rstudio/secure-cookie-key
    owner: root
    group: root
    mode: 0600
  when:
    - rstudio_workbench_secure_cookie_key is defined
    - rstudio_workbench_secure_cookie_key|length
