---

- name: configure | update (server) configuration file
  template:
    src: etc/rstudio/rserver.conf.j2
    dest: /etc/rstudio/rserver.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - rstudio-workbench-configure-server

- name: configure | create (SSO metadata xml) file
  copy:
    content: "{{ rstudio_workbench_sso_saml_metadata_content_b64_encoded | b64decode }}"
    dest: "{{ rstudio_workbench_sso_saml_metadata_file_path }}"
    owner: rstudio-server
    group: root
    mode: 0600
  when:
    - rstudio_workbench_sso_saml_metadata_content_b64_encoded|d()
    - rstudio_workbench_sso_saml_metadata_file_path|d()

- name: configure | update (session) configuration file
  template:
    src: etc/rstudio/rsession.conf.j2
    dest: /etc/rstudio/rsession.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - rstudio-workbench-configure-session

- name: configure | logging configuration file
  template:
    src: etc/rstudio/logging.conf.j2
    dest: /etc/rstudio/logging.conf
    owner: root
    group: root
    mode: 0644
  when:
    - rstudio_workbench_logging_config is defined
  tags:
    - rstudio-workbench-configure-logging

- name: configure | create (database) configuration file
  template:
    src: etc/rstudio/database.conf.j2
    dest: /etc/rstudio/database.conf
    owner: root
    group: root
    mode: 0600
  when:
    - rstudio_workbench_database_config is defined
  tags:
    - rstudio-workbench-configure-database

- name: configure | update (profiles) configuration file
  template:
    src: etc/rstudio/profiles.j2
    dest: /etc/rstudio/profiles
    owner: root
    group: root
    mode: 0644
  when:
    - rstudio_workbench_profiles_config is defined
  tags:
    - rstudio-workbench-configure-profiles

- name: configure | update pam profile
  template:
    src: etc/pam.d/rstudio.j2
    dest: /etc/pam.d/rstudio
    owner: root
    group: root
    mode: 0644
  when:
    - rstudio_workbench_pam_profile is defined
  tags:
    - rstudio-workbench-configure-pam-profile

- name: configure | create sssd service config
  template:
    src: etc/sssd/sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600
  notify:
    - restart sssd
  when:
    - rstudio_workbench_sssd_config is defined
  tags:
    - rstudio-workbench-configure-sssd

- include: configure-lb.yml
  when:
    - rstudio_workbench_load_balancer_config is defined
    - rstudio_workbench_database_config is defined
    - rstudio_workbench_secure_cookie_key is defined
    - rstudio_workbench_secure_cookie_key|length
  tags:
    - rstudio-workbench-configure-load-balancer

- name: configure | make sure shared-storage directory exists
  file:
    path: "{{ rstudio_workbench_rserver_config['server-shared-storage-path'] }}"
    state: directory
    mode: 0755
  when:
    - rstudio_workbench_rserver_config['server-shared-storage-path'] is defined

- name: configure | make sure shared users home directory exists
  file:
    path: "{{ rstudio_workbench_users_home_dir }}"
    state: directory
    mode: 0755
  when:
    - rstudio_workbench_users_home_dir is defined

- include: configure-launcher.yml
  notify:
    - restart rstudio-job-launcher
  tags:
    - rstudio-workbench-configure-launcher

- name: configure | create (openid) configuration file
  template:
    src: etc/rstudio/openid-client-secret.j2
    dest: /etc/rstudio/openid-client-secret
    owner: root
    group: root
    mode: 0600
  when:
    - rstudio_workbench_openid_config is defined
  tags:
    - rstudio-workbench-configure-openid

- name: configure | link (env-vars) file
  file:
    src: "{{ rstudio_workbench_env_vars_file_path }}"
    dest: /etc/rstudio/env-vars
    owner: root
    group: root
    state: link
  when:
    - rstudio_workbench_env_vars_file_path is defined
    - rstudio_workbench_env_vars_file_path|length
    - rstudio_workbench_env_vars is not defined
  tags:
    - rstudio-workbench-configure-env-vars

- name: configure | create (env-vars) file
  template:
    src: etc/rstudio/env-vars.j2
    dest: /etc/rstudio/env-vars
    owner: root
    group: root
    mode: 0644
  when:
    - rstudio_workbench_env_vars is defined
  tags:
    - rstudio-workbench-configure-env-vars

- name: configure | create (repos.conf) file
  template:
    src: etc/rstudio/repos.conf.j2
    dest: /etc/rstudio/repos.conf
    owner: root
    group: root
    mode: 0644
  when:
    - rstudio_workbench_repos_config is defined
  tags:
    - rstudio-workbench-configure-repos

- name: configure | activate server license
  shell: |
    /usr/sbin/rstudio-server license-manager activate {{ rstudio_workbench_license }}
  notify: restart rstudio-workbench
  when: rstudio_workbench_license|d()
  no_log: true
  register: license_output
  tags:
    - rstudio-workbench-configure-license
