---
- name: configure | update (server) configuration file
  template:
    src: etc/rstudio/rserver.conf.j2
    dest: /etc/rstudio/rserver.conf
    owner: root
    group: root
    mode: 0644
  notify: restart rstudio-workbench
  tags:
    - rstudio-workbench-configure-server

- name: configure | activate server license
  shell: |
    /usr/sbin/rstudio-server license-manager activate {{ rstudio_workbench_license }}
  notify: restart rstudio-server
  when: rstudio_workbench_manager_license|d()
  register: license_output
  tags:
    - rstudio-workbench-configure-migration
