---

- name: install pro-drivers | install dependencies
  ansible.builtin.apt:
    name: "{{ rstudio_workbench_pro_drivers_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"

- name: install pro-drivers | download deb
  ansible.builtin.get_url:
    url: "{{ rstudio_workbench_pro_drivers_download_url }}"
    dest: "{{ rstudio_workbench_downloads_path }}/rstudio-drivers_{{ rstudio_workbench_pro_drivers_version }}_{{ rstudio_workbench_machine_map[ansible_machine] }}.deb"
    mode: 0644
    owner: root
    group: root

- name: install pro-drivers | install deb
  ansible.builtin.apt:
    deb: "{{ rstudio_workbench_downloads_path }}/rstudio-drivers_{{ rstudio_workbench_pro_drivers_version }}_{{ rstudio_workbench_machine_map[ansible_machine] }}.deb"

- name: configure pro-drivers | create odbcinst.ini
  ansible.builtin.copy:
    src: /opt/rstudio-drivers/odbcinst.ini.sample
    dest: /etc/odbcinst.ini
    mode: 0644
    owner: root
    group: root
    remote_src: true

...
