# tasks file
---
- name: Include variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "_{{ ansible_distribution_release }}.yml"
    - "_{{ ansible_distribution | lower }}.yml"
    - _default.yml
  tags: always

- name: Import install tasks
  ansible.builtin.import_tasks: install.yml
  notify: Restart rstudio-workbench
  tags: install

- name: Import configure tasks
  ansible.builtin.import_tasks: configure.yml
  notify: Restart rstudio-workbench
  tags: configure

- name: Start and enable service
  ansible.builtin.service:
    name: rstudio-server
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
