# tasks file
---
- name: include variables
  include_vars: "{{ item }}"
  with_first_found:
    - "_{{ ansible_distribution_release }}.yml"
    - "_{{ ansible_distribution | lower }}.yml"
    - _default.yml
  tags:
    - configuration
    - rstudio-workbench
    - rstudio-workbench-include-variables

- include: install.yml
  tags:
    - configuration
    - rstudio-workbench
    - rstudio-workbench-install
  notify: restart rstudio-workbench

- include: configure.yml
  tags:
    - configuration
    - rstudio-workbench
    - rstudio-workbench-configure
  notify: restart rstudio-workbench

- include: install-r.yml
  tags:
    - r-version-install

- include: install-drivers.yml
  when: rstudio_workbench_pro_drivers_install

- name: start and enable service
  service:
    name: rstudio-server
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - rstudio-workbench
    - rstudio-workbench-start-enable-service
