# handlers file
---
- name: restart rstudio-workbench
  service:
    name: rstudio-server
    state: restarted
  when: service_default_state | default('started') == 'started'

- name: restart rstudio-job-launcher
  service:
    name: rstudio-launcher
    state: restarted
  when: service_default_state | default('started') == 'started'

- name: restart sssd
  service:
    name: sssd
    state: restarted
  when: service_default_state | default('started') == 'started'
