# handlers file
---
- name: restart rstudio-workbench
  ansible.builtin.service:
    name: rstudio-server
    state: restarted
  when: service_default_state | default('started') == 'started'

- name: restart rstudio-job-launcher
  ansible.builtin.service:
    name: rstudio-launcher
    state: restarted
  when: service_default_state | default('started') == 'started'

- name: restart sssd
  ansible.builtin.service:
    name: sssd
    state: restarted
  when: service_default_state | default('started') == 'started'
